name: wire
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.10.16
  - pip
  - cython>=0.29.0
# numpy universe
  - numpy>=1.16.5
  - matplotlib>=3.0.3
  - scikit-learn
  - scikit-image>=0.14.1
  - scipy==1.11.1 # scipy 1.12.0 will cause FID computation to fail (sqrtm will produce complex matrix)
# deep learning 
  - pytorch::pytorch-cuda=12.4
  - pytorch::pytorch==2.4.1
  - pytorch::torchvision
  - pytorch::torchaudio

# system, file io, testing
  - tqdm>=4.28.1
  - pyyaml>=3.13
  - pip:
    - einops
    - timm
    - diffusers
    - accelerate
    - beartype
    - ema_pytorch
    - einx
    - x_transformers==2.0.0
    - torchtyping
    - jaxtyping
    - wandb
    - Deprecated
    - pytorch_custom_utils
    - torchdiffeq
    - open3d
    